default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: game_collection_manager_development

test:
  <<: *default
  database: game_collection_manager_test

production:
  <<: *default
  database: game_collection_manager_production
